baseURL: "https://quito418.github.io/"
title: Quito418 PR
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

- name: GitHub Pages action
  uses: peaceiris/actions-gh-pages@v3.7.3

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Quito418 PR
  description: "Quito418 PR Blog"
  #  keywords: [Blog, Portfolio, PaperMod]
  keywords: [Blog, Portfolio]
  author: Me
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / https://github.com/quito418/quito418/person.png>"
    favicon16x16: "<link / https://github.com/quito418/quito418/person.png>"
    favicon32x32: "<link / https://github.com/quito418/quito418/person.png>"
    apple_touch_icon: "https://github.com/quito418/quito418/person.png"
    #safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: https://github.com/quito418/quito418/raw/master/document.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    #- name: twitter
    #  url: "https://twitter.com/"
    #- name: stackoverflow
    #  url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/quito418"


  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    #bing:
    #  SiteVerificationTag: "XYZabc"
    #yandex:
    #  SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/quito418/quito418_blog/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: AboutMe
      name: About Me
      url: https://quito418.github.io/quito418/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai